# Generated by Django 2.2.10 on 2020-02-27 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawnews',
            name='origin_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
