# Generated by Django 2.2.10 on 2020-02-27 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200227_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawnews',
            name='article_url',
            field=models.URLField(unique=True),
        ),
    ]
