# Generated by Django 2.2.10 on 2020-03-12 15:25

import api.models
from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200228_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawnews',
            name='meta',
            field=djongo.models.fields.EmbeddedField(blank=True, model_container=api.models.TagHolder, model_form_class=api.models.TagHolderForm, null=True),
        ),
    ]
