# Generated by Django 2.2.10 on 2020-03-11 12:59

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200228_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawnews',
            name='tags',
            field=djongo.models.fields.ListField(default=[], null=True),
        ),
    ]
