# Generated by Django 2.2.10 on 2020-03-12 13:57

import api.models
from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rawnews_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawnews',
            name='tags',
        ),
        migrations.AddField(
            model_name='rawnews',
            name='meta',
            field=djongo.models.fields.EmbeddedField(model_container=api.models.TagHolder, model_form_class=api.models.TagHolderForm, null=True),
        ),
    ]
